Init discord.js, discordx and prisma.js
nplay-team/moderation-bot pull request #6
Opened 2024-05-22 15:05 UTC by SachsenspieltCoding

Mit diesem PR wird discord.js und das Command-Framework discordx grundlegend implementiert.
Zusätzlich wird prisma.js als ORM für MySQL hinzugefügt und ein erstes Datenbank-Schema wurde erstellt. Dieses sollte aber vorerst nocheimal diskutiert werden, ob das für alle so in Ordnung geht.

Gerne einmal hier Feedback geben.

2024-05-22 19:13 UTC, SachsenspieltCoding commented
> Wenn ich das richtig verstehe soll im Model Report der User derjenige sein, der reported hat und userid soll auf den verweisen der reported würde. Wenn das so stimmt würde ich das Attribut nicht User nennen sondern reporter oder so, ist für mich eindeutiger,

user und userId wäre in diesem Fall der Reportete, der Reporter (Moderator) ist der reporter bzw. reporterId

2024-05-22 19:16 UTC, Glukose1 commented
Ok, Dann muss ich sagen finde ich fast ein bisschen overkill User name und user id zu speichern. eigentlich reicht doch auch die User ID als FK oder übersehe ich da was wichtiges?

2024-05-22 19:18 UTC, SachsenspieltCoding commented
Es wird nur die userId in der DB gespeichert. Das user (und reporter) Field ist nur ein higher level feature von prisma, sodass man diese direkt über eine "Query" mit aufrufen kann.

2024-05-22 19:21 UTC, Glukose1 commented
Ahh, ok. Das war mir so nicht bekannt. Danke für die Klarstellung.

2024-05-23 09:14 UTC, Kaktushose requested changes
Wir sollten die reports im sinne der Normalisierung in eine eigene Tabelle auslagern und dort speichern, auch ist fraglich, ob wir eine eigene Tabelle für user brauchen, theoretisch reicht uns die snowflake id.

2024-05-23 09:14 UTC, Kaktushose commented on prisma/schema.prisma
> +  createdAt DateTime @default(now())
sehe ich keinen nutzen drin

2024-05-23 09:14 UTC, Kaktushose commented on prisma/schema.prisma
> +  updatedAt DateTime @updatedAt
ebenso

2024-05-23 09:14 UTC, Kaktushose commented on prisma/schema.prisma
> +  reports        Report[] @relation(name: "Report_User")
wir sollten das nicht als array auf dem user speichern

2024-05-23 09:14 UTC, Kaktushose commented on prisma/schema.prisma
> +  BAN
TEMP_BAN sollte ein eigener Type sein

2024-05-23 09:14 UTC, Kaktushose commented on prisma/schema.prisma
> +  reports Report[]
redundant, kann man auch über eine query abfragen

2024-05-23 09:14 UTC, Kaktushose commented on prisma/schema.prisma
> +  reporter   User   @relation(name: "Report_Reporter", fields: [reporterId], references: [id])
vllt. in issuer umbenennen?

2024-05-23 09:22 UTC, SachsenspieltCoding commented on prisma/schema.prisma
> +  createdAt DateTime @default(now())
Bei den usern können wir es zwecks Speicheroptimierung tatsächlich rausnehmen, obwohl es jetzt im Backend theoretisch keinen Unterschied machen würde.

2024-05-23 09:22 UTC, SachsenspieltCoding commented on prisma/schema.prisma
> +  updatedAt DateTime @updatedAt
siehe Oben

2024-05-23 09:23 UTC, SachsenspieltCoding commented on prisma/schema.prisma
> +  reports        Report[] @relation(name: "Report_User")
Das Array muss da sein, sonst meckert Prisma. Es hat aber keinen Einfluss auf die DB, da ist es eine ganz normale 1-n-Beziehung.

2024-05-23 09:23 UTC, SachsenspieltCoding commented on prisma/schema.prisma
> +  BAN
Jo, können wir einfügen

2024-05-23 09:24 UTC, SachsenspieltCoding commented on prisma/schema.prisma
> +  reports Report[]
Selbiges hier, das ist eine Vorgabe durch prisma und lässt sich nicht umgehen

2024-05-23 09:25 UTC, SachsenspieltCoding commented
> Wir sollten die reports im sinne der Normalisierung in eine eigene Tabelle auslagern und dort speichern, auch ist fraglich, ob wir eine eigene Tabelle für user brauchen, theoretisch reicht uns die snowflake id.

Meinst du dann eine Trennung von Report und Moderativer Aktion (Warn, Ban, Kick, ...)?

2024-05-24 14:49 UTC, Kaktushose commented
Müssen wir die user überhaupt in der datenbank speichern? Gegenwärtig haben wir ja keine Daten die wir user specific speichern. Oder war das nur angedacht für eventuelle zukünftige features? 

die delDays müssen wir nicht speichern, die werden ja nur beim bann einmal an discord gesendet und sind danach nicht mehr von nutzen. 

Die guildId muss glaube ich auch nicht gespeichert werden, der bot läuft ja nur auf einem server

2024-05-24 14:52 UTC, SachsenspieltCoding commented
> Müssen wir die user überhaupt in der datenbank speichern? Gegenwärtig haben wir ja keine Daten die wir user specific speichern. Oder war das nur angedacht für eventuelle zukünftige features?

Ich hab das jetzt einfach mal reingenommen, sollten wir das mal zukünftig benötigen. Ich mein, das braucht ja jetzt nicht ewig viel Speicher, sodass es so denke ich mal angenehmer ist, als im Zweifel später mittels DB Migration das alles zu verknüpfen.

> die delDays müssen wir nicht speichern, die werden ja nur beim bann einmal an discord gesendet und sind danach nicht mehr von nutzen.

Ah jo, da hast du natürlich recht. Mein Fehler.

> Die guildId muss glaube ich auch nicht gespeichert werden, der bot läuft ja nur auf einem server

Ich hätte den Bot jetzt aufgrund der geringen Komplexität Mutli-Guild fähig ausgelegt. Ist kein großer Mehraufwand und lässt nach oben hin einfach etwas Luft. Kann man natürlich jetzt diskutieren, ob man das braucht

2024-05-24 14:54 UTC, SachsenspieltCoding commented
Achtung, ich hab meine Antwort nochmal bearbeitet!

2024-05-24 15:17 UTC, Kaktushose commented
1. passt dann so
2. ja könnte man rein nehmen 
3. ja können wir auch multi guild machen, am ende musst du ja den code schreiben :D kollidiert dann nur beim permissions table solange die id der PK ist, wenn ein user auf mehreren guilds ist und unterschiedliche perms haben soll. role ids sind ja immer unique, da ist das kein problem

2024-05-24 15:38 UTC, Glukose1 approved these changes
Ich würde sagen das passt so.

2024-05-24 15:43 UTC, Kaktushose approved these changes

2024-05-24 15:44 UTC, merged